version: '3'
services:
    web:
        container_name: nginx
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        container_name: php
        build:
            context: .
            dockerfile: Dockerfile.php
        volumes:
            - ./code:/code
        env_file:
            - ./.env       
    mysql:
        container_name: mysql
        image: mysql:5.7.22
        volumes:
            - ./data/db:/var/lib/mysql
        restart: always
        env_file:
            - ./.env
        ports:
            - "3306:3306"
    node:
        container_name: node
        working_dir: /code
        image: node:10.14.2-alpine
        volumes:
            - ./code:/code
        command: npm install